graph_file_path: "/opt/SungemSDK-GraphModels/graphs/graph_object_SSD"
category_file_path: "/opt/SungemSDK-GraphModels/misc/voc21.txt"
network_dimension: 300
channel1_mean: 127.5
channel2_mean: 127.5
channel3_mean: 127.5
scale: 0.007843
