graph_file_path: "/opt/SungemSDK-GraphModels/graphs/graph_mobilenets"
category_file_path: "/opt/SungemSDK-GraphModels/misc/imagenet1001.txt"
network_dimension: 224
channel1_mean: 127.5
channel2_mean: 127.5
channel3_mean: 127.5
scale: 0.007843
