graph_file_path: "/opt/SungemSDK-GraphModels/graphs/graph_inception_v3"
category_file_path: "/opt/SungemSDK-GraphModels/misc/imagenet1001.txt"
network_dimension: 299
channel1_mean: 128
channel2_mean: 128
channel3_mean: 128
scale: 0.0078125
